apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    uid: aff6siwyp8y68e
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: 126523
    jsonData:
      database: engineering_dashboard
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true