{
 "title": "Engineering Telemetry Dashboard",
 "time": { "from": "2026-03-06T17:40:17.447Z", "to": "2026-03-06T17:44:04.001Z" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "SELECT DISTINCT\r\n  device_name AS __value,\r\n  REPLACE(device_name, 'sensor_', '') AS __text\r\nFROM telemetry\r\nORDER BY __value;"
    }
   },
   {
    "name": "device_label",
    "query": {
     "query": "SELECT DISTINCT\r\n  device_name AS __value,\r\n  initcap(replace(device_name, '_', ' ')) AS __text\r\nFROM telemetry\r\nORDER BY device_name;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Telemetry Delay",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\nEXTRACT(EPOCH FROM (NOW() - MAX(time))) AS delay_seconds\r\nFROM telemetry"
    }
   ]
  },
  {
   "title": "Total Telemetry Messages (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT COUNT(*) \r\nFROM telemetry\r\nWHERE time >= NOW() - INTERVAL '24 hours'"
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN MAX(time) > NOW() - INTERVAL '2 minutes' THEN 1\r\n    ELSE 0\r\n  END AS device_status\r\nFROM telemetry"
    }
   ]
  },
  {
   "title": "Messages by Sensor (24h)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\ndevice_name,\r\nCOUNT(*) AS messages\r\nFROM telemetry\r\nWHERE $__timeFilter(time)\r\nGROUP BY device_name\r\nORDER BY messages DESC;"
    }
   ]
  },
  {
   "title": "online statusd panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\ndevice_name,\r\nMAX(time) AS last_seen,\r\nCASE\r\n  WHEN MAX(time) > NOW() - INTERVAL '10 minutes'\r\n  THEN 'ONLINE'\r\n  ELSE 'OFFLINE'\r\nEND AS status\r\nFROM telemetry\r\nGROUP BY device_name\r\nORDER BY device_name;"
    }
   ]
  },
  {
   "title": " ${device_label} Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "repeat": "device_label",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\n $__time(time),\r\n temperature AS \"Temperature (°C)\",\r\n humidity AS \"Humidity (%)\"\r\nFROM telemetry\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature - ${device_label}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "repeat": "device_label",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\n  temperature\r\nFROM telemetry\r\nWHERE device_name IN (${device:sqlstring})\r\nORDER BY time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Humidity -   ${device_label}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "repeat": "device_label",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\n  humidity\r\nFROM telemetry\r\nWHERE device_name IN (${device:sqlstring})\r\nORDER BY time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "${device_label} - Latest Telemetry  ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "repeat": "device_label",
   "targets": [
    { "dataset": "engineering_dashboard" },
    {
     "dataset": "engineering_dashboard",
     "rawSql": "SELECT\r\n  time,\r\n  temperature,\r\n  humidity\r\nFROM telemetry\r\nWHERE device_name IN (${device:sqlstring})\r\nORDER BY time DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}